### ISSUE TITLE
thisvishalsingh - thisvishalsingh - `Tranche::issue` Unbound `underlyingAmount` can cause Denial of Service attack

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-napier-judging#23]
thisvishalsingh

medium

# thisvishalsingh - `Tranche::issue` Unbound `underlyingAmount` can cause Denial of Service attack

thisvishalsingh

High

# `Tranche::issue` Unbound `underlyingAmount` can cause a Denial of Service attack.

## Summary
Enforcing a bounded `underlyingAmount` token to be deposited can prevent attackers from clogging the network with zero amount or dust transactions.

## Vulnerability Detail
`issue` can process a limited amount of underlying tokens to be deposited in each call, an attacker can push `underlyingAmount` an enormous number with amount = 0. 
To stop the DoS attack and process the issuance of `underlyingAmount`, the governance needs to spend as much gas as the attacker. if the governance doesn't have enough money to pay for the gas, the `issue` can't be processed.

## Impact
Malicious users can lock up all the leverage issued Principal Token and Yield Token in exchange for `underlyingAmount` offered by Napier Tranche causing denial-of-service. 
This results in a loss of funds for the protocol as the `Tranche` is no longer issuing PT and YT tokens, so no profit for the protocol, and also a loss of funds for users as they cannot realize the profits because they are forced to exit the `Tranche` prematurely.

The following are various reasons why someone would want to perform a DOS on Napier `Tranche::issue`:

- Damage the reputation of Napier, and reduce users' trust in Napier
- A competitor who is also offering  similar tech attempts to bring down Napier
- Someone who shorted Napier's protocol token

## Code Snippet
https://github.com/sherlock-audit/2024-01-napier/blob/main/napier-v1/src/Tranche.sol#L207

## Tool used

Manual Review

## Recommendation 
Disallow  `underlyingAmount` below a certain threshold to maintain efficiency and prevent denial of service through dust spamming. e.g. 1 dollar

**Comment by this-vishalsingh** [comment]
@sherlock-admin Without any reason how you can close it? proof me wrong
