### ISSUE TITLE
thisvishalsingh - thisvishalsingh - Centralisation risk: admin role of `BaseLSTAdapter::setRebalancer` can rug pull all Eth from the adapter.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-napier-judging#26]
thisvishalsingh

medium

# thisvishalsingh - Centralisation risk: admin role of `BaseLSTAdapter::setRebalancer` can rug pull all Eth from the adapter.

## Found by
thisvishalsingh

# M-1: Centralization Risk for Trusted Owners can rug pull all Eth from the adapter.

## Summary
Contracts have owners with privileged rights to perform admin tasks and need to be trusted to not perform malicious updates or drain funds.

## Vulnerability Detail
 1. Found in src/adapters/BaseLSTAdapter.sol [Line: 245](src/adapters/BaseLSTAdapter.sol#L245)

- There is a Centralisation risk of the Adapter for Liquid Staking Token where the `rebalancer` of `BaseLSTAdapter.sol` is able to modify the ERC20 token address to any arbitrary address.  
- And Missing checks for `address(0)` when assigning values to address state variables results in `address(0)` to new owner who can request withdrawal.

```solidity
	    function setRebalancer(address _rebalancer) external onlyOwner {
                    rebalancer = _rebalancer;
             }
```
where given that:
```solidity
/// @notice Rebalancer of the ETH buffer, can be set by the owner
    /// @notice The account can request a withdrawal
    address public rebalancer;
```
- This change is critical for Napier Finance and its users, allowing the admin to pull any assets from the pool. The best practice is to track the protocol fee and only allow access to that amount. 

- Critical privileges MUST be transferred via a two-step process and the protocol MUST behave as expected before/during/after transfer.

- Also missing event: Events are often used to monitor the protocol status. Without the emission of events, users might be affected due to ignorance of the changes.

- There is no proper validation in privileged setter `setRebalancer` function: The validation on the protocol configuration values is often overlooked assuming the admin is trusted. But it is always recommended clarifying the range of each configuration value and validate in setter functions. (e.g. protocol fee should be limited)

2. Found in src/BaseAdapter.sol [Line: 15](src/BaseAdapter.sol#L15)

	```solidity
	abstract contract BaseAdapter is Ownable2Step, IBaseAdapter {
	```

## Impact
Admin can rug all user funds in every Adapter deployed by changing the `rebalancer` address.
Centralization vulnerabilities usually require a malicious or a compromised account and are of Medium severity

## Code Snippet
https://github.com/sherlock-audit/2024-01-napier/blob/main/napier-v1/src/adapters/BaseLSTAdapter.sol#L245

https://github.com/sherlock-audit/2024-01-napier/blob/main/napier-v1/src/BaseAdapter.sol#L15

## Tool used

Manual Review

## Recommendation

- Reconsider if the `setRebalancer`is a mandatory mechanism for the protocol.
- If the functionality is required ensure it is behind a time lock and multisig / dao.

Duplicate of #99

**Comment by this-vishalsingh** [comment]
@sherlock-admin Without any reason how you can close it?
